from fpdf import FPDF
from datetime import datetime
import io

class MalariaReport(FPDF):
    def header(self):
        # Logo placeholder or Title
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 10, 'Malaria AI Diagnosis Report', 0, 1, 'C')
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 10, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(patient_id, diagnosis, confidence, severity):
    """Generates a professional clinical PDF report."""
    pdf = MalariaReport()
    pdf.add_page()
    
    # Patient Information Section
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, 'Patient Information', 1, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 10, f'Patient ID: {patient_id}', 0, 1)
    pdf.ln(5)
    
    # Diagnosis Results Section
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Diagnosis Results', 1, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 11)
    
    # Set color based on diagnosis
    if diagnosis == "Parasitized":
        pdf.set_text_color(200, 0, 0) # Red
    else:
        pdf.set_text_color(0, 150, 0) # Green
        
    pdf.cell(0, 10, f'Diagnosis: {diagnosis}', 0, 1)
    pdf.set_text_color(0, 0, 0) # Reset to black
    
    pdf.cell(0, 10, f'AI Confidence Score: {confidence:.2%}', 0, 1)
    pdf.cell(0, 10, f'Clinical Severity: {severity}', 0, 1)
    pdf.ln(10)
    
    # Disclaimer
    pdf.set_font('Helvetica', 'I', 9)
    pdf.multi_cell(0, 10, 'Disclaimer: This report is generated by an Artificial Intelligence system and is intended for screening assistance only. It should be reviewed by a qualified medical professional for final clinical confirmation.')
    
    # Return PDF as bytes
    return bytes(pdf.output())
